%% Visualizing the output of EX2 of the Modflow 2000 manual.
% TO 091011 091129 120413 140112
 
%% Get data
load('name.mat') % get basename stored in file name.mat
load(basename);  % having retrieved baasename load the data in basename.mat
load underneath  % to get gr object

% Read head file
H=readDat([basename,'','.hds']);

% Generate suitable set of contour levels
hrange=ContourRange(H,50);

%% Plot isolines of head
figure('pos',screenPos(0.6));

P=[0 0 0.4 0.4]; % size of subaxis

fsz=10; % fontsize to use in figure

% Create axes at their desired position
ax(1)=axes('position', [0.05 0.55 0 0]+P,'nextplot','add','fontsize',fsz);
ax(2)=axes('position', [0.55 0.55 0 0]+P,'nextplot','add','fontsize',fsz);
ax(3)=axes('position', [0.05 0.05 0 0]+P,'nextplot','add','fontsize',fsz);
ax(4)=axes('position', [0.55 0.05 0 0]+P,'nextplot','add','fontsize',fsz,...
        'xColor',grey,'yColor',grey,'color','k','ticklength',[0 0]);

% Make a contour plot for all (3) layers
for iLay = 1:gr.Nlay
    set(gca,'clim',hrange([1 end]));
    
    xlabel(ax(iLay),'x [1000ft]');
    ylabel(ax(iLay),'y [1000ft]');
    title( ax(iLay), sprintf('head in layer %d',iLay))

    % Contour layer iLay
    [c,hdl]=contourf(ax(iLay),gr.xm,gr.ym,H(end).values(:,:,iLay),hrange,'edgecolor','none');
    clabel(c,hdl); % plot contour labels

    % Plot wells in this layer
    Iw = find([well.iLay]==iLay);
    for iw = 1:length(Iw)
        well(iw).plotXY(ax(iLay),'or');
    end

    % Plot drain
    if iLay==1, plot(ax(iLay),drn(:,1),drn(:,2),'color','g','linewidth',2); end
    
end

% Use forth axis to put informative text into
s={'Example from MODFLOW 2000 manual, p89';''; 'Computed in mfLab';''; 'TO 2012-04-07'};
text(0.5,0.5,s,'HorizontalAlignment','center','color','yellow','fontsize',fsz);

%% Use zone budget to get budget overview

B=readBud6([basename, '.bgt']); % read the Budget file

% Generate an array with zones for use in zonebudget (one zone per layer)
zoneArray =bsxfun(@times,ones(gr.Ny,gr.Nx),XS([1; 2; 3]));

% Show budget of each of the zones
zonebudget(B,zoneArray,[1 2 3]);

%% Show particles
% Read the particles from the files that were generated by Modpath.
% Be aware that this takes several minutes. Progress will be indicated
% using dots.

figure('pos',screenPos(0.5)); hold on; xlabel('x [m]'); ylabel('y [m]'); zlabel('z [m]');
title('Path lines, backward traces from all wells');
pGrp = pGrp.getEndPoints('mp6.endp');  % add endpoints to pGrp (particle groups)
pGrp.endPointStatistics();             % show endpoint statistics.
pGrp.plotEndPoints('k.');              % plot the endpoints
pGrp.plotStartPoints('b.');            % plot the start points

% Adapt properties of current axis for better view on plot.
% The picture can be rotated by hand using the roation tool in the toolbar
% of the figure window.
set(gca,'xlim',gr.xGr([1 end]),'ylim',gr.yGr([end 1]),'zlim',gr.zGr([end 1]), ...
        'xgrid','on','ygrid','on','zgrid','on');

pGrp = pGrp.getPathLines('mp6.plines'); % read the path lines
pGrp.plotPath();                        % plot them.
view(3);                                % use a 3D view

% -------------- END ------------------------------------

