function ZTA = zetaClean(gr,ZTA)
% ZTA = gr.zetaClean(ZTA)
% where ZTA is read by ZTA = readBud(zetafile);
% with zetafile generated by the SWI package
% sets all values of zeta coinciding with bottom of top of layer to NaN
% so that they will not be plotted.
% TO 120927


for it=1:length(ZTA)
    for iterm = 1:length(ZTA(it).term)
        for iLay = 1:gr.Nlay
            ZTA(it).term{iterm}(ZTA(it).term{iterm}>gr.ZTlay-gr.MINDZ)=NaN;
            ZTA(it).term{iterm}(ZTA(it).term{iterm}<gr.ZBlay+gr.MINDZ)=NaN;
        end
    end
end
