function B=maskBud(B,MASK,lbls)
%MASKBUD sets B(i).term{j}(:) to 0 for values>MASK or values<MASK for values==0
%
% USAGE:
%    B=function maskBud(B,MASK)
%
%    B is a struct generated by readBud. See readBud for details.
%
% MASK is an array or scalar
%    if mask is array (such as IBOUND) all values corresponding to zeros in
%    mask are set to zero rather than NaN
%    if mask is a scalar, such as HNOFLOW or HDRY then
%    if mask>0 all values > 0.999*MASK are set  to 0
%    if mask<0 all values < 0.999*MASK are set  to 0
%    if mask=0 all values equal to zero are set to 0
%
% See also   maskHC readBud readDat readMT3D
%
% TO 090315 100420 100718 100911 120408

% Copyright 2009-2013 Theo Olsthoorn, TU-Delft and Waternet, without any warranty
% under free software foundation GNU license version 3 or later

if ~isnumeric(MASK)
    error('maskBud:argin:secondArgMustBeDouble',...
        'Second arguments must be a scalar or a double array of size B(i).term{j}\n');
elseif ~all(size(MASK)==1)
    if any([size(MASK,1),size(MASK,2),size(MASK,3)]~=size(B(1).term{1}))
        error('maskBud:argin:sizeOfMaskArray',...
            'Size of MASK (%d,%d,%d) does not match size of B(1).term{j} (%d,%d,%d)\n',...
            size(MASK,1),size(MASK,2),size(MASK,3),size(B(1).term{1}));
    end
end
    
threshold=0.999;  % to prevent roundoff errors

if exist('lbls','var') && ~isempty(lbls)
    if ischar(lbls)
        lbls={lbls};
    else
        if ~iscell(lbls) && ~ischar(lbls{1})
            error('maskBud:lbls:mustbelistofstrings',...
                'Thrid argument in maskBud must be a string or series of strings in cells.\n');
        end
    end
end

for it=1:length(B)
    if ~exist('lbls','var') || isempty('lbls')
        if isscalar(MASK)
            for iLbl=1:length(B(it).label)
                if MASK>0, B(it).term{iLbl}(B(it).term{iLbl}>threshold*MASK)=0; end
                if MASK<0, B(it).term{iLbl}(B(it).term{iLbl}<threshold*MASK)=0; end
                if MASK==0,B(it).term{iLbl}(B(it).term{iLbl}==MASK)=0; end
            end
        end
    else
        for iL=1:length(lbls)
            iLbl=strmatchi(lbls{iL},B(it).label); iLbl=iLbl(1);
            if iLbl>0
                if MASK>0, B(it).term{iLbl}(B(it).term{iLbl}>threshold*MASK)=0; end
                if MASK<0, B(it).term{iLbl}(B(it).term{iLbl}<threshold*MASK)=0; end
                if MASK>0, B(it).term{iLbl}(B(it).term{iLbl}==MASK)=0; end
            end
        end
    end
end