% VISUALIZATION
%
% Files
%   animateXS           - script to get an animateObj and to run an animation with movie creation
%   animator_loglog     - allows picking data series on screen with mouse and moving them (on logscale).
%   arrow               - draw/plot an arrow
%   circle              - plots a circle
%   clrObj              - class definition for color objects to plot on multiple axis with distinct colors (obsolete)
%   dist                - computes distance in m between two googleMap points
%   geoAddress          - retrieves the Lat Lon coordinates of a legal google maps address
%   getRegisIIXS        - Retrieves a cross section from the TNO dino loket website
%   googleMap           - geneates a google Map object
%   googlemapObj        - class def for google map objects
%   grey                - color grey, often used to draw less hard lines [0.8 0.8 0.8]
%   isLineSpec          - check if lineSpec is a legal Matlab lineSpec
%   jet3                - colormap with grey in the middle red on top and blue on bottom
%   map2rgb             - converts flat image with colormap map to RGB
%   mf_3Dblock          - plots a 3D block with cutout defined by ix,iy,iz
%   mf_color            - yields next in color series and restarts after last color has been used
%   mf_colormap         - make your own colormap of size [L,3] using colors 'b r g k m c y w'
%   mf_contourRange     - computes suitable range of contour levels
%   mf_GM2PIC           - retrieves a goolge map image as png file to show simulation results on map
%   mf_GM2PNG           - retrieves a GM image as png file by calling mf_GM2PIC
%   mf_GM_PIC_LL        - retrieves a goolge map image and puts it in Lat Lon axis
%   mf_GM_PIC_XY        - retrieves a goolge map image and puts it in Lat Lon axis
%   mf_GM_tile_size     - computes size of pixel in m according to zoom level
%   mf_GMlat2y          - computes googles Y from Laititute
%   mf_GMLL2pix         - GMLL2PIX translates lat lon to pix coordinates on local GM tile
%   mf_GMLL2XY          - computes XY and d in m of LL ralative to NC EC
%   mf_GMlon2x          - computes googles x from Longitude
%   mf_GMpix2LL         - computes lat long from local pix coordinates given GM tile and zoom level.
%   mf_GMpix2m          - computes lat long from local pix coordinates given GM tile and zoom level.
%   mf_GMpix2XY         - computes dist in m to zero meridian and equator
%   mf_GMpixsizeinm     - computes size of pixel in m according to zoom level
%   mf_GMTiles          - translates lat lon to pix coordinates on local GM tile
%   mf_GMx2lon          - computes googles x from Longitude
%   mf_GMy2lat          - computes Latitude from googles y
%   mf_linetype         - yields next in ltype series and restarts after last line type has been used
%   mf_marker           - yields next in series and switches back to one when length of markers is reached
%   mf_setmulticolormap - sets colormap and cmap so that multiple color schemes can be used on the same axes.
%   mf_wireframe        - plots wireframe definend by arguments
%   msgObj              - Places a message box on the figure and allows dynamic updating of the
%   pix2LL              - convert PIX coordinates to Lat Lon
%   plotEndPoints       - plots the endpoints in MODPATH6 endpoint file named fname
%   plotMPathLocations  - plot  MPath locations made by gr.startLoc in 3D
%   plotPath            - plots the MODPATH6 path lines of the particle groups
%   plotStartPoints     - plots the endpoints in MODPATH6 endpoint file named fname
%   plotTsrPoints       - plots the time series points generated by MODPATH6
%   rgb                 - rgb triple for given CSS color name
%   screenPos           - gives position of figure, so that fig is centralized and its size is given fraction of screen size
%   showArray           - shows an array with an outcut through cell ix,iy,iz
%   showLayers          - a GUI for showing and observing 3D layers with wells and mesh
