function h = plotTsrPoints(tsrFName,lSpec)
%PLOTTSRPOINTS  plots the time series points generated by MODPATH6
%
% Example:
%    hdl = plotTsrPoints(tsrFname[,lSpec])
%
% where lSpec is a lineSpec as valid for plot(x,y,lSpec)
% Notic: first load the time series points with
%    pgrp = pgrp.getParticles
%
% See also: plotPath plotEndPoints plotStartPoints
%
% TO 130219
    
    tsr = readTsrPoints(tsrFName);
    
    ix = strmatchi('xG',tsr.colHdr);
    iy = strmatchi('yG',tsr.colHdr);
    iz = strmatchi('zG',tsr.colHdr);
    
    NGrp = unique(tsr.P(:,5));
    h(NGrp) = NaN;
    
    for iGrp = NGrp(:)'
        if nargin<2
            lSpec = [mf_color(iGrp,'brgkmc'),mf_marker(iGrp,'o*^sp+x')];
        end
        I = find(tsr.P(:,5)==iGrp);
        if nargin<2
            lSpec = [mf_color(iGrp,'brgkmc'),mf_marker(iGrp,'o*^sp+x')];
        end
        h(iGrp) = plot3(tsr.P(I,ix),tsr.P(I,iy),tsr.P(I,iz),lSpec);
    end
    h(h==0)=[];
end
