%% Script mf_adapt.m for NHI (netherlands hydrologic instrument)
%
% This script should guide you through the NHI site (www.nhi.nu).
%
% This mfile uses published NHI data, which have bee downloaded and stored
% lcoally in mat files in the directory mflab/examples/NHI/NHIdata.
%
% The matfiles have been generated by mflab/mfiles/NHI.
%
% A type descripion has been added to each of the files, to facilitate
% automation for using the data for generating submodels of the NHI.
%
% Generate a model around the coordinates of one of the pumping test
% locations stored in the file NHI.xls.
% Run that file to regenerate them.
% Alternatively you can run mf_build from this directory.
%
% TO 120430

basename ='NHI';
location = 'Lexmond';

names = {'gr' 'TRAN' 'C' 'STRTHD' 'WEL' 'DRN' 'GHB0' 'RIV0' 'RECH'};

for i = numel(names):-1:1
    load(['NHIdata' filesep names{i}]);
end

HY = TRAN./gr.DZlay; % HY required for convertable layers (LAYCON==3)

GHB=GHB0;
RIV=RIV0;

%% Set the layer to 2 for all RIV, GHB and DRN that have a layer thickness of less
% than 1 m. This works.If the cover layer is minimal as it was at many
% locations, wetting does not work.

if 1   % set 1 to 0 to demonstrate that this action is necessary
    coverThreshold = 1.0; %m

    fprintf('Lowering the layer number if layer thickness < %g m\n',coverThreshold);

    % Get global indices for RIV stress cells
    Idx = cellIndex(RIV(:,[4 3 2]),gr.size);
    
    % See which of them are in a cover layer thinner than coverThreshold
    tooThin = gr.DZlay(Idx)<coverThreshold;
    
    % Move these stresses one layer down
    RIV(tooThin,2)=RIV(tooThin,2)+1;
    
    % Communicate how many have been moved down
    fprintf('%d  RIV points lowered\n',sum(tooThin)); 

    % Same for GHB
    Idx = cellIndex(GHB(:,[4 3 2]),gr.size);
    tooThin = gr.DZlay(Idx)<coverThreshold;
    GHB(tooThin,2)=GHB(tooThin,2)+1;
    fprintf('%d  GHB points lowered\n',sum(tooThin)); 

    % Same for DRN
    Idx = cellIndex(DRN(:,[4 3 2]),gr.size);
    tooThin = gr.DZlay(Idx)<coverThreshold;
    DRN(tooThin,2)=DRN(tooThin,2)+1;
    fprintf('%d  DRN points lowered\n',sum(tooThin)); 
end

